// Event statuses
export type EventStatus = 'created' | 'announced' | 'cancelled' | 'finished' | 'finalized' | 'paid'

// Day of week
export type DayOfWeek = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun'

// Scaffold
export interface Scaffold {
  id: string
  day_of_week: DayOfWeek
  time: string // HH:MM format
  default_courts: number
  is_active: boolean
  announcement_deadline?: string
}

// Event
export interface Event {
  id: string
  scaffold_id?: string
  datetime: Date
  courts: number
  status: EventStatus
  telegram_message_id?: string
  payment_message_id?: string
  announcement_deadline?: string
}

// Participant
export interface Participant {
  id: string
  telegram_username?: string
  telegram_id?: string
  display_name: string
}

// EventParticipant
export interface EventParticipant {
  id?: number // Auto-generated by DB
  event_id: string
  participant_id: string
  participations: number
}

// Payment
export interface Payment {
  id?: number // Auto-generated by DB
  event_id: string
  participant_id: string
  amount: number
  is_paid: boolean
  paid_at?: Date
  reminder_count: number
}

// Settings
export interface Settings {
  key: string
  value: string
}
