// Event statuses
export type EventStatus = 'created' | 'announced' | 'cancelled' | 'finished' | 'finalized' | 'paid'

// Day of week
export type DayOfWeek = 'Mon' | 'Tue' | 'Wed' | 'Thu' | 'Fri' | 'Sat' | 'Sun'

// Scaffold
export interface Scaffold {
  id: string
  dayOfWeek: DayOfWeek
  time: string // HH:MM format
  defaultCourts: number
  isActive: boolean
  announcementDeadline?: string
}

// Event
export interface Event {
  id: string
  scaffoldId?: string
  datetime: Date
  courts: number
  status: EventStatus
  telegramMessageId?: string
  paymentMessageId?: string
  announcementDeadline?: string
}

// Participant
export interface Participant {
  id: string
  telegramUsername?: string
  telegramId?: string
  displayName: string
}

// EventParticipant
export interface EventParticipant {
  id?: number // Auto-generated by DB
  eventId: string
  participantId: string
  participations: number
}

// Payment
export interface Payment {
  id?: number // Auto-generated by DB
  eventId: string
  participantId: string
  amount: number
  isPaid: boolean
  paidAt?: Date
  reminderCount: number
}

// Settings
export interface Settings {
  key: string
  value: string
}
